spring:
  cache:
    type: simple
  codec:
    max-in-memory-size: 128MB
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:100MB}
      max-request-size: ${MAX_REQUEST_SIZE:100MB}
  mvc:
    async:
      request-timeout: -1
  application:
    name: ai_hub
  datasource:
    name: ${spring.application.name}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS:152.136.51.36:19029}/aihub?useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Ecgp5CaFM0wVYhyeixSZKTOHIbrPZZHf}
#    url: jdbc:mysql://${MYSQL_ADDRESS:localhost:3306}/aihub?useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true
#    username: ${MYSQL_USERNAME:root}
#    password: ${MYSQL_PASSWORD:123456}
  freemarker:
    cache: true
  flyway:
    baseline-on-migrate: true
#    baseline-on-migrate: on
  cas:
    sign-out-filters: /logout
    auth-filters: /*
    validate-filters: /*
    request-wrapper-filters: /*
    assertion-filters: /*
    cas-server-login-url: http://10.1.5.102:18080/cas/login
    cas-server-url-prefix: http://10.1.5.102:18080/cas
    redirect-after-validation: true
    use-session: true
    server-name: http://192.168.81.23:8012


server:
  port: ${SERVER_PORT:9876}
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  swagger-ui:
    enabled: true
#    enabled: on

auth:
  default-password: ${DEFAULT_PASSWORD:goodluck}

s3:
  access-key-id: ${S3_ACCESS_KEY:MCwX7dMkmCjBUlfHkpSJ}
  secret-access-key: ${S3_SECRET_KEY:GR0hiRMUWzacM2SdgFDH3T64VM5wCTHTiB0i7vsu}
  endpoint: ${S3_ENDPOINT:http://192.168.2.56:9000}
  public-endpoint: ${S3_PUBLIC_ENDPOINT:http://113.108.105.54:56800/store}
  buckets:
    tmpfile: ${S3_TMPFILE_BUCKET:tmpfile}
    document: ${S3_DOCUMENT_BUCKET:document}
    blocked: ${S3_BLOCKED_BUCKET:blocked}

jwt:
  jwt-key: ${JWT_PRIVATE_KEY:D:/delete/aihub/jpk}
#  jwt-key: ${JWT_PRIVATE_KEY:/opt/keys/jwt_key}
  key-id: ${JWT_KEY_ID:good_luck}
  issuer: ${JWT_ISSUER:happy}
  audience: ${JWT_AUDIENCE:happy}
  expiration: ${JWT_TOKEN_EXPIRATION:24h}
  # 临近超时时间10分钟内，会返回新的token
  refresh-interval: ${JWT_TOKEN_REFRESH_INTERVAL:2h}
  head: ${JWT_TOKEN_HEAD:auth}


langchain4j:
  ollama:
    streaming-chat-model:
      base-url: ${OLAMA_CHAT_MODEL_BASE_URL:http://localhost:11434}
      model-name: ${OLAMA_CHAT_MODEL_NAME:qwen2.5:14b}
      log-requests: false
      log-responses: false
#      log-requests: off
#      log-responses: off
    chat-model:
      base-url: ${OLAMA_CHAT_MODEL_BASE_URL:http://localhost:11434}
      model-name: ${OLAMA_CHAT_MODEL_NAME:qwen2.5:14b}
      log-requests: true
      log-responses: true
#      log-requests: on
#      log-responses: on
logging:
  level:
    dev.langchain4j.http.client.log: debug
