spring:
  cache:
    type: simple
  codec:
    max-in-memory-size: 128MB
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:100MB}
      max-request-size: ${MAX_REQUEST_SIZE:100MB}
  mvc:
    async:
      request-timeout: -1
  application:
    name: ai_hub
  datasource:
    name: ${spring.application.name}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS:localhost:3306}/aihub2?useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    hikari:
      max-lifetime: 300000
      keepalive-time: 60000
      connection-test-query: select 1
  freemarker:
    cache: true
  flyway:
    baseline-on-migrate: on
  elasticsearch:
    uris: ${ELASTIC_URIS:http://localhost:9200}
    username: ${ELASTIC_USERNAME:elastic}
    password: ${ELASTIC_PASSWORD:changeme}

server:
  port: ${SERVER_PORT:9876}
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  swagger-ui:
    enabled: on

auth:
  default-password: ${DEFAULT_PASSWORD:goodluck}

s3:
  access-key-id: ${S3_ACCESS_KEY:sHKl9cOI3zB6ZGXDOMRG}
  secret-access-key: ${S3_SECRET_KEY:M12ZDky1IIFIHRUj06M1LdL22fOQZTBOudpVjVLq}
  endpoint: ${S3_ENDPOINT:http://192.168.2.50:9000}
  public-endpoint: ${S3_PUBLIC_ENDPOINT:http://113.108.105.54:56800/store2}
  buckets:
    tmpfile: ${S3_TMPFILE_BUCKET:tmpfile}
    document: ${S3_DOCUMENT_BUCKET:document}
    blocked: ${S3_BLOCKED_BUCKET:blocked}

jwt:
  jwt-key: ${JWT_PRIVATE_KEY:/opt/keys/jwt_key}
  key-id: ${JWT_KEY_ID:good_luck}
  issuer: ${JWT_ISSUER:happy}
  audience: ${JWT_AUDIENCE:happy}
  expiration: ${JWT_TOKEN_EXPIRATION:24h}
  # 临近超时时间10分钟内，会返回新的token
  refresh-interval: ${JWT_TOKEN_REFRESH_INTERVAL:2h}
  head: ${JWT_TOKEN_HEAD:auth}

model:
  ollama-llm:
    base-url: ${OLAMA_CHAT_MODEL_BASE_URL:http://localhost:11434}
    model-name: ${OLAMA_CHAT_MODEL_NAME:deepseek-r1:1.5b}
    log-requests: on
    log-responses: off
    timeout: 1m

langchain4j:
  ollama:
    streaming-chat-model:
      base-url: ${OLAMA_CHAT_MODEL_BASE_URL:http://localhost:11434}
      model-name: ${OLAMA_CHAT_MODEL_NAME:deepseek-r1:1.5b}
      log-requests: off
      log-responses: off
    chat-model:
      base-url: ${OLAMA_CHAT_MODEL_BASE_URL:http://localhost:11434}
      model-name: ${OLAMA_CHAT_MODEL_NAME:deepseek-r1:1.5b}
      log-requests: on
      log-responses: on
logging:
  level:
    dev.langchain4j.http.client.log: debug
